version: '3'
services:
    db:
        image: "postgres:11.7"
        ports:
            - "28043:5432"
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=postgres
        volumes:
            - c14-db-data-dev-indocare:/var/lib/postgresql/data
        container_name: postgresql-14-ee-dev-indocare
    odoo:
        image: "invosasystems/odoo-invosa:14.0"
        ports:
            - "8082:8069"
        volumes:
            - c14-odoo-data-dev-indocare:/var/lib/odoo
            - /home/oatmeal/dev-INDOCARE/custom/ee14:/mnt/ins-addons
            - /home/oatmeal/dev-INDOCARE/backups/ee14:/mnt/odoo-backups
            - /home/oatmeal/dev-INDOCARE/logs/:/mnt/odoo-logs
            - /home/oatmeal/dev-INDOCARE/conf/odoo.conf:/etc/odoo/odoo.conf

        container_name: odoo-14-ee-dev-indocare
        restart: always
        links:
            - db:db

volumes:
    c14-db-data-dev-indocare:
    c14-odoo-data-dev-indocare:

